language: ruby
sudo: false
bundler_args: --jobs 4 --retry 2 --without packaging documentation
before_install:
  - gem update --system && gem install bundler --no-document
script:
  - "bundle exec rake pr:check"
notifications:
  email: false
rvm:
  - 2.6.2
